# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 03:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pyconguide.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pyconguide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=pyconguide.models.uuid_hex, max_length=32, verbose_name='Slug')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Updated')),
                ('icalendar', models.TextField(blank=True, verbose_name='iCalendar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
