# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyconguide', '0003_auto_20160529_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='icalendar',
        ),
    ]
