# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyconguide', '0006_auto_20160529_0822'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presentation',
            unique_together=set([('pycon', 'presentation_id')]),
        ),
    ]
